# sims args
sim: armax
T: -1
dt: 0.02
T_updates: 20 #  20/0.02 = 1000 points =, sps taking max 18 (start), min 8 seconds
plot_system: true
history_limit: 5.0 # seconds
dB: sim_data.db
apply_disturbance: true
disturbance: 50
controller: lqr
L: [[-1.2]] # 2.7 x optimal F
Q: [[0.9, 0.0], [0.0, 0.4]] # state x state
R: [[1.0]] # input x input
reference: [square]
r_a: [1.0] # when using constant reference
r_f: [0.4]
r_c: [0.0]
A: [1.0, -0.7, -0.1]
B: [0.0, -0.4, -0.2]
C: [1.0]
# sps args
n_A: 2
n_B: 2
n_states: 2
n_inputs: 1
n_outputs: 1
n_refs: 1
n_noise_order: -1
C_obs: [[0, 1]] # observation matrix
n_points: [40, 40, 40, 10]
m: 100
q: 5
N: 200
debug: true
epsilon: 1e-10
Lambda: [[1, 0], [0, 1]]
search: radial # grid or radial
bounds: [[-1.5,0], [-0.7, 0.2], [-0.8, 0.2], [-1, 0.0]]
forget: 0.0
random_centers: 300
steepness: 200
