# sims args
sim: water_tank
T: -1
dt: 0.01
T_updates: 15 #  10/0.02 = 500 points =, sps taking max 18 (start), min 8 seconds
plot_system: true
history_limit: 5.0 # seconds
dB: sim_data.db
apply_disturbance: true
disturbance: 50
controller: lqr
L: [[0.1]] # 2.7 x optimal F
reference: [sin]
r_a: [0.55] # when using constant reference
r_f: [0.07]
r_c: [1.0]
# sps args
n_A: 1
n_B: 1
n_states: 1
n_inputs: 1
n_outputs: 1
n_refs: 1
n_noise_order: -1
C_obs: [[1]] # observation matrix
n_points: [100, 100]
m: 100
q: 5
N: 200
debug: true
epsilon: 1e-10
Lambda: [[1, 0], [0, 1]]
search: radial # grid or radial
bounds: [[-1.25,-0.75], [-0.25, 0.25]]
forget: 0.01
random_centers: 200
